-- Vacantes de ejemplo (contenido de relleno, genérico, sin empresas ni
-- personas reales) para que la app no se vea vacía a los primeros usuarios.
-- Pedido explícito del dueño del producto -- ver CLAUDE.md, sección
-- "Vacantes de ejemplo (contenido de relleno)".
--
-- Cómo identificarlas y borrarlas en bloque más adelante (cuando empiecen a
-- entrar ofertas reales de empresas de verdad): las 10 empresas reservadas
-- de este seed tienen "legalId" = 'EJEMPLO' y su correo sigue el patrón
-- ejemplo.<categoria>@mexicosinhambre.com. Borrar esas filas de "users"
-- borra en cascada sus company_profiles y TODAS sus job_postings:
--
--   DELETE FROM "users" WHERE "email" LIKE 'ejemplo.%@mexicosinhambre.com';
--
-- (Cascada: users -> company_profiles -> job_postings, todas las relaciones
-- ya tienen onDelete: Cascade en el schema actual, sin migración nueva.)

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_construccion', 'ejemplo.construccion@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_construccion', 'seed_ejemplo_user_construccion', 'Contratista de Construcción', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.construccion@mexicosinhambre.com', 'Ciudad de México', 'Construcción y obra', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_hoteles-turismo', 'ejemplo.hoteles-turismo@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_hoteles-turismo', 'seed_ejemplo_user_hoteles-turismo', 'Hotel y Turismo Local', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.hoteles-turismo@mexicosinhambre.com', 'Guadalajara', 'Hoteles y turismo', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_restaurantes', 'ejemplo.restaurantes@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_restaurantes', 'seed_ejemplo_user_restaurantes', 'Restaurante Local', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.restaurantes@mexicosinhambre.com', 'Monterrey', 'Restaurantes', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_limpieza', 'ejemplo.limpieza@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_limpieza', 'seed_ejemplo_user_limpieza', 'Servicios de Limpieza', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.limpieza@mexicosinhambre.com', 'Puebla', 'Limpieza', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_transporte', 'ejemplo.transporte@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_transporte', 'seed_ejemplo_user_transporte', 'Empresa de Transporte', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.transporte@mexicosinhambre.com', 'Querétaro', 'Transporte', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_seguridad', 'ejemplo.seguridad@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_seguridad', 'seed_ejemplo_user_seguridad', 'Empresa de Seguridad Privada', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.seguridad@mexicosinhambre.com', 'Mérida', 'Seguridad privada', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_oficinas-administracion', 'ejemplo.oficinas-administracion@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_oficinas-administracion', 'seed_ejemplo_user_oficinas-administracion', 'Oficina Administrativa', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.oficinas-administracion@mexicosinhambre.com', 'Tijuana', 'Oficinas y administración', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_ventas-comercio', 'ejemplo.ventas-comercio@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_ventas-comercio', 'seed_ejemplo_user_ventas-comercio', 'Comercio Local', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.ventas-comercio@mexicosinhambre.com', 'León', 'Ventas y comercio', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_tecnologia', 'ejemplo.tecnologia@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_tecnologia', 'seed_ejemplo_user_tecnologia', 'Empresa de Tecnología', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.tecnologia@mexicosinhambre.com', 'Toluca', 'Tecnología', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "users" ("id", "email", "passwordHash", "role", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_user_profesionales', 'ejemplo.profesionales@mexicosinhambre.com', '$2a$10$EjemploNoEsUnaContrasenaRealXXXXXXXXXXXXXXX', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "company_profiles" ("id", "userId", "commercialName", "legalId", "responsibleName", "contactPhone", "contactEmail", "location", "activity", "description", "isVerified", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_company_profesionales', 'seed_ejemplo_user_profesionales', 'Despacho Profesional', 'EJEMPLO', 'Cuenta de ejemplo', NULL, 'ejemplo.profesionales@mexicosinhambre.com', 'Cancún', 'Servicios profesionales', 'Cuenta de ejemplo usada para publicar vacantes de relleno mientras la app suma empresas reales.', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_01', 'seed_ejemplo_company_construccion', 'Albañil con experiencia', 'Buscamos albañil con experiencia para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Ciudad de México', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-08-28T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_02', 'seed_ejemplo_company_construccion', 'Ayudante de construcción', 'Buscamos ayudante de construcción para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Guadalajara', 'TIEMPO_COMPLETO', '$7,000 - $9,000 MXN al mes', true, '2026-08-21T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_03', 'seed_ejemplo_company_construccion', 'Electricista residencial', 'Buscamos electricista residencial para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Monterrey', 'MEDIO_TIEMPO', '$7,500 - $9,500 MXN al mes', true, '2026-08-14T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_04', 'seed_ejemplo_company_construccion', 'Plomero/fontanero', 'Buscamos plomero/fontanero para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Puebla', 'TIEMPO_COMPLETO', '$8,000 - $9,500 MXN al mes', true, '2026-08-07T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_05', 'seed_ejemplo_company_construccion', 'Pintor de interiores y exteriores', 'Buscamos pintor de interiores y exteriores para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Querétaro', 'POR_HORAS', '$8,000 - $10,000 MXN al mes', true, '2026-07-31T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_06', 'seed_ejemplo_company_construccion', 'Maestro de obras', 'Buscamos maestro de obras para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Mérida', 'TIEMPO_COMPLETO', '$8,500 - $10,500 MXN al mes', true, '2026-07-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_07', 'seed_ejemplo_company_construccion', 'Soldador', 'Buscamos soldador para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Tijuana', 'TIEMPO_COMPLETO', '$9,000 - $10,500 MXN al mes', true, '2026-07-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_08', 'seed_ejemplo_company_construccion', 'Techista (instalación de techos)', 'Buscamos techista (instalación de techos) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'León', 'MEDIO_TIEMPO', '$9,000 - $11,000 MXN al mes', true, '2026-08-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_09', 'seed_ejemplo_company_construccion', 'Operador de maquinaria pesada', 'Buscamos operador de maquinaria pesada para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Toluca', 'TIEMPO_COMPLETO', '$9,500 - $11,500 MXN al mes', true, '2026-08-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_construccion_10', 'seed_ejemplo_company_construccion', 'Carpintero de obra', 'Buscamos carpintero de obra para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'CONSTRUCCION', 'Cancún', 'POR_HORAS', '$10,000 - $11,500 MXN al mes', true, '2026-08-10T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_01', 'seed_ejemplo_company_hoteles-turismo', 'Mesero/a para restaurante', 'Buscamos mesero/a para restaurante para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'San Luis Potosí', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-08-03T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_02', 'seed_ejemplo_company_hoteles-turismo', 'Camarera de hotel', 'Buscamos camarera de hotel para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Aguascalientes', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-07-27T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_03', 'seed_ejemplo_company_hoteles-turismo', 'Guía turístico bilingüe', 'Buscamos guía turístico bilingüe para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Culiacán', 'MEDIO_TIEMPO', '$7,500 - $9,000 MXN al mes', true, '2026-07-20T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_04', 'seed_ejemplo_company_hoteles-turismo', 'Recepcionista de hotel', 'Buscamos recepcionista de hotel para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Chihuahua', 'TIEMPO_COMPLETO', '$7,500 - $9,000 MXN al mes', true, '2026-08-27T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_05', 'seed_ejemplo_company_hoteles-turismo', 'Cocinero/a', 'Buscamos cocinero/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Veracruz', 'POR_HORAS', '$8,000 - $9,500 MXN al mes', true, '2026-08-20T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_06', 'seed_ejemplo_company_hoteles-turismo', 'Ayudante de cocina', 'Buscamos ayudante de cocina para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Hermosillo', 'TIEMPO_COMPLETO', '$8,000 - $9,500 MXN al mes', true, '2026-08-13T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_07', 'seed_ejemplo_company_hoteles-turismo', 'Bartender', 'Buscamos bartender para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Oaxaca', 'TIEMPO_COMPLETO', '$8,500 - $10,000 MXN al mes', true, '2026-08-06T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_08', 'seed_ejemplo_company_hoteles-turismo', 'Chofer para tours', 'Buscamos chofer para tours para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Tampico', 'MEDIO_TIEMPO', '$8,500 - $10,000 MXN al mes', true, '2026-07-30T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_09', 'seed_ejemplo_company_hoteles-turismo', 'Encargado/a de limpieza en hotel', 'Buscamos encargado/a de limpieza en hotel para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Ciudad de México', 'TIEMPO_COMPLETO', '$9,000 - $10,500 MXN al mes', true, '2026-07-23T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_hoteles-turismo_10', 'seed_ejemplo_company_hoteles-turismo', 'Coordinador/a de eventos y turismo', 'Buscamos coordinador/a de eventos y turismo para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'HOTELES_TURISMO', 'Guadalajara', 'POR_HORAS', '$9,500 - $11,000 MXN al mes', true, '2026-07-16T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_01', 'seed_ejemplo_company_restaurantes', 'Cocinero/a de línea', 'Buscamos cocinero/a de línea para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Monterrey', 'TIEMPO_COMPLETO', '$6,000 - $7,500 MXN al mes', true, '2026-08-23T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_02', 'seed_ejemplo_company_restaurantes', 'Ayudante de cocina (turno noche)', 'Buscamos ayudante de cocina (turno noche) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Puebla', 'TIEMPO_COMPLETO', '$6,500 - $8,000 MXN al mes', true, '2026-08-16T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_03', 'seed_ejemplo_company_restaurantes', 'Mesero/a de tiempo completo', 'Buscamos mesero/a de tiempo completo para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Querétaro', 'MEDIO_TIEMPO', '$6,500 - $8,000 MXN al mes', true, '2026-08-09T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_04', 'seed_ejemplo_company_restaurantes', 'Cajero/a de restaurante', 'Buscamos cajero/a de restaurante para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Mérida', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-08-02T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_05', 'seed_ejemplo_company_restaurantes', 'Repartidor/a de comida a domicilio', 'Buscamos repartidor/a de comida a domicilio para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Tijuana', 'POR_HORAS', '$7,000 - $8,500 MXN al mes', true, '2026-07-26T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_06', 'seed_ejemplo_company_restaurantes', 'Lavaloza / lavaplatos', 'Buscamos lavaloza / lavaplatos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'León', 'TIEMPO_COMPLETO', '$7,500 - $9,000 MXN al mes', true, '2026-07-19T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_07', 'seed_ejemplo_company_restaurantes', 'Barista', 'Buscamos barista para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Toluca', 'TIEMPO_COMPLETO', '$7,500 - $9,000 MXN al mes', true, '2026-08-26T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_08', 'seed_ejemplo_company_restaurantes', 'Pastelero/a', 'Buscamos pastelero/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Cancún', 'MEDIO_TIEMPO', '$8,000 - $9,500 MXN al mes', true, '2026-08-19T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_09', 'seed_ejemplo_company_restaurantes', 'Anfitrión/a de salón', 'Buscamos anfitrión/a de salón para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'San Luis Potosí', 'TIEMPO_COMPLETO', '$8,000 - $9,500 MXN al mes', true, '2026-08-12T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_restaurantes_10', 'seed_ejemplo_company_restaurantes', 'Gerente/a de restaurante', 'Buscamos gerente/a de restaurante para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'RESTAURANTES', 'Aguascalientes', 'POR_HORAS', '$8,500 - $10,000 MXN al mes', true, '2026-08-05T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_01', 'seed_ejemplo_company_limpieza', 'Personal de limpieza para oficinas', 'Buscamos personal de limpieza para oficinas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Culiacán', 'TIEMPO_COMPLETO', '$6,000 - $7,000 MXN al mes', true, '2026-07-29T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_02', 'seed_ejemplo_company_limpieza', 'Personal de limpieza para casas particulares', 'Buscamos personal de limpieza para casas particulares para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Chihuahua', 'TIEMPO_COMPLETO', '$6,000 - $7,500 MXN al mes', true, '2026-07-22T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_03', 'seed_ejemplo_company_limpieza', 'Supervisor/a de limpieza', 'Buscamos supervisor/a de limpieza para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Veracruz', 'MEDIO_TIEMPO', '$6,500 - $7,500 MXN al mes', true, '2026-07-15T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_04', 'seed_ejemplo_company_limpieza', 'Auxiliar de limpieza industrial', 'Buscamos auxiliar de limpieza industrial para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Hermosillo', 'TIEMPO_COMPLETO', '$6,500 - $7,500 MXN al mes', true, '2026-08-22T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_05', 'seed_ejemplo_company_limpieza', 'Camarista (limpieza de habitaciones)', 'Buscamos camarista (limpieza de habitaciones) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Oaxaca', 'POR_HORAS', '$7,000 - $8,000 MXN al mes', true, '2026-08-15T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_06', 'seed_ejemplo_company_limpieza', 'Limpieza de cristales y fachadas', 'Buscamos limpieza de cristales y fachadas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Tampico', 'TIEMPO_COMPLETO', '$7,000 - $8,000 MXN al mes', true, '2026-08-08T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_07', 'seed_ejemplo_company_limpieza', 'Personal de limpieza para centros comerciales', 'Buscamos personal de limpieza para centros comerciales para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Ciudad de México', 'TIEMPO_COMPLETO', '$7,000 - $8,000 MXN al mes', true, '2026-08-01T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_08', 'seed_ejemplo_company_limpieza', 'Encargado/a de lavandería', 'Buscamos encargado/a de lavandería para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Guadalajara', 'MEDIO_TIEMPO', '$7,500 - $8,500 MXN al mes', true, '2026-07-25T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_09', 'seed_ejemplo_company_limpieza', 'Limpieza post-construcción', 'Buscamos limpieza post-construcción para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Monterrey', 'TIEMPO_COMPLETO', '$7,500 - $8,500 MXN al mes', true, '2026-07-18T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_limpieza_10', 'seed_ejemplo_company_limpieza', 'Auxiliar de limpieza para eventos', 'Buscamos auxiliar de limpieza para eventos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'LIMPIEZA', 'Puebla', 'POR_HORAS', '$8,000 - $9,000 MXN al mes', true, '2026-08-25T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_01', 'seed_ejemplo_company_transporte', 'Chofer de camión de carga', 'Buscamos chofer de camión de carga para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Querétaro', 'TIEMPO_COMPLETO', '$7,500 - $9,500 MXN al mes', true, '2026-08-18T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_02', 'seed_ejemplo_company_transporte', 'Chofer repartidor', 'Buscamos chofer repartidor para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Mérida', 'TIEMPO_COMPLETO', '$8,000 - $10,000 MXN al mes', true, '2026-08-11T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_03', 'seed_ejemplo_company_transporte', 'Motociclista repartidor', 'Buscamos motociclista repartidor para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Tijuana', 'MEDIO_TIEMPO', '$8,000 - $10,000 MXN al mes', true, '2026-08-04T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_04', 'seed_ejemplo_company_transporte', 'Chofer de transporte de personal', 'Buscamos chofer de transporte de personal para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'León', 'TIEMPO_COMPLETO', '$8,500 - $10,500 MXN al mes', true, '2026-07-28T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_05', 'seed_ejemplo_company_transporte', 'Operador/a de montacargas', 'Buscamos operador/a de montacargas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Toluca', 'POR_HORAS', '$9,000 - $11,000 MXN al mes', true, '2026-07-21T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_06', 'seed_ejemplo_company_transporte', 'Ayudante de mudanzas', 'Buscamos ayudante de mudanzas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Cancún', 'TIEMPO_COMPLETO', '$9,500 - $11,000 MXN al mes', true, '2026-08-28T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_07', 'seed_ejemplo_company_transporte', 'Chofer con licencia tipo E', 'Buscamos chofer con licencia tipo e para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'San Luis Potosí', 'TIEMPO_COMPLETO', '$9,500 - $11,500 MXN al mes', true, '2026-08-21T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_08', 'seed_ejemplo_company_transporte', 'Despachador/a de flotilla', 'Buscamos despachador/a de flotilla para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Aguascalientes', 'MEDIO_TIEMPO', '$10,000 - $12,000 MXN al mes', true, '2026-08-14T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_09', 'seed_ejemplo_company_transporte', 'Chofer para plataforma de viajes', 'Buscamos chofer para plataforma de viajes para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Culiacán', 'TIEMPO_COMPLETO', '$10,500 - $12,500 MXN al mes', true, '2026-08-07T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_transporte_10', 'seed_ejemplo_company_transporte', 'Auxiliar de logística y almacén', 'Buscamos auxiliar de logística y almacén para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TRANSPORTE', 'Chihuahua', 'POR_HORAS', '$10,500 - $12,500 MXN al mes', true, '2026-07-31T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_01', 'seed_ejemplo_company_seguridad', 'Guardia de seguridad para oficinas', 'Buscamos guardia de seguridad para oficinas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Veracruz', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-07-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_02', 'seed_ejemplo_company_seguridad', 'Guardia de seguridad nocturno', 'Buscamos guardia de seguridad nocturno para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Hermosillo', 'TIEMPO_COMPLETO', '$7,000 - $8,500 MXN al mes', true, '2026-07-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_03', 'seed_ejemplo_company_seguridad', 'Guardia de seguridad para centro comercial', 'Buscamos guardia de seguridad para centro comercial para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Oaxaca', 'MEDIO_TIEMPO', '$7,500 - $9,000 MXN al mes', true, '2026-08-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_04', 'seed_ejemplo_company_seguridad', 'Escolta personal', 'Buscamos escolta personal para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Tampico', 'TIEMPO_COMPLETO', '$7,500 - $9,000 MXN al mes', true, '2026-08-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_05', 'seed_ejemplo_company_seguridad', 'Supervisor/a de seguridad', 'Buscamos supervisor/a de seguridad para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Ciudad de México', 'POR_HORAS', '$8,000 - $9,500 MXN al mes', true, '2026-08-10T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_06', 'seed_ejemplo_company_seguridad', 'Operador/a de cámaras (CCTV)', 'Buscamos operador/a de cámaras (cctv) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Guadalajara', 'TIEMPO_COMPLETO', '$8,000 - $9,500 MXN al mes', true, '2026-08-03T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_07', 'seed_ejemplo_company_seguridad', 'Guardia de seguridad para eventos', 'Buscamos guardia de seguridad para eventos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Monterrey', 'TIEMPO_COMPLETO', '$8,500 - $10,000 MXN al mes', true, '2026-07-27T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_08', 'seed_ejemplo_company_seguridad', 'Guardia de seguridad residencial', 'Buscamos guardia de seguridad residencial para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Puebla', 'MEDIO_TIEMPO', '$8,500 - $10,000 MXN al mes', true, '2026-07-20T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_09', 'seed_ejemplo_company_seguridad', 'Personal de control de acceso', 'Buscamos personal de control de acceso para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Querétaro', 'TIEMPO_COMPLETO', '$9,000 - $10,500 MXN al mes', true, '2026-08-27T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_seguridad_10', 'seed_ejemplo_company_seguridad', 'Custodio/a de valores', 'Buscamos custodio/a de valores para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'SEGURIDAD', 'Mérida', 'POR_HORAS', '$9,500 - $11,000 MXN al mes', true, '2026-08-20T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_01', 'seed_ejemplo_company_oficinas-administracion', 'Auxiliar administrativo/a', 'Buscamos auxiliar administrativo/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Tijuana', 'TIEMPO_COMPLETO', '$8,000 - $10,000 MXN al mes', true, '2026-08-13T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_02', 'seed_ejemplo_company_oficinas-administracion', 'Recepcionista de oficina', 'Buscamos recepcionista de oficina para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'León', 'TIEMPO_COMPLETO', '$8,500 - $10,500 MXN al mes', true, '2026-08-06T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_03', 'seed_ejemplo_company_oficinas-administracion', 'Auxiliar contable', 'Buscamos auxiliar contable para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Toluca', 'MEDIO_TIEMPO', '$9,000 - $11,000 MXN al mes', true, '2026-07-30T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_04', 'seed_ejemplo_company_oficinas-administracion', 'Capturista de datos', 'Buscamos capturista de datos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Cancún', 'TIEMPO_COMPLETO', '$9,000 - $11,500 MXN al mes', true, '2026-07-23T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_05', 'seed_ejemplo_company_oficinas-administracion', 'Asistente de dirección', 'Buscamos asistente de dirección para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'San Luis Potosí', 'POR_HORAS', '$9,500 - $11,500 MXN al mes', true, '2026-07-16T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_06', 'seed_ejemplo_company_oficinas-administracion', 'Encargado/a de archivo y documentación', 'Buscamos encargado/a de archivo y documentación para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Aguascalientes', 'TIEMPO_COMPLETO', '$10,000 - $12,000 MXN al mes', true, '2026-08-23T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_07', 'seed_ejemplo_company_oficinas-administracion', 'Auxiliar de recursos humanos', 'Buscamos auxiliar de recursos humanos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Culiacán', 'TIEMPO_COMPLETO', '$10,500 - $12,500 MXN al mes', true, '2026-08-16T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_08', 'seed_ejemplo_company_oficinas-administracion', 'Coordinador/a de compras', 'Buscamos coordinador/a de compras para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Chihuahua', 'MEDIO_TIEMPO', '$11,000 - $13,000 MXN al mes', true, '2026-08-09T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_09', 'seed_ejemplo_company_oficinas-administracion', 'Auxiliar de facturación', 'Buscamos auxiliar de facturación para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Veracruz', 'TIEMPO_COMPLETO', '$11,000 - $13,500 MXN al mes', true, '2026-08-02T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_oficinas-administracion_10', 'seed_ejemplo_company_oficinas-administracion', 'Secretario/a ejecutivo/a', 'Buscamos secretario/a ejecutivo/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'OFICINAS_ADMINISTRACION', 'Hermosillo', 'POR_HORAS', '$11,500 - $13,500 MXN al mes', true, '2026-07-26T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_01', 'seed_ejemplo_company_ventas-comercio', 'Vendedor/a de piso (tienda)', 'Buscamos vendedor/a de piso (tienda) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Oaxaca', 'TIEMPO_COMPLETO', '$7,000 - $9,000 MXN al mes', true, '2026-07-19T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_02', 'seed_ejemplo_company_ventas-comercio', 'Cajero/a de tienda', 'Buscamos cajero/a de tienda para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Tampico', 'TIEMPO_COMPLETO', '$7,500 - $9,500 MXN al mes', true, '2026-08-26T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_03', 'seed_ejemplo_company_ventas-comercio', 'Encargado/a de sucursal', 'Buscamos encargado/a de sucursal para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Ciudad de México', 'MEDIO_TIEMPO', '$8,000 - $10,000 MXN al mes', true, '2026-08-19T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_04', 'seed_ejemplo_company_ventas-comercio', 'Promotor/a de ventas', 'Buscamos promotor/a de ventas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Guadalajara', 'TIEMPO_COMPLETO', '$8,000 - $10,500 MXN al mes', true, '2026-08-12T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_05', 'seed_ejemplo_company_ventas-comercio', 'Vendedor/a de mostrador', 'Buscamos vendedor/a de mostrador para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Monterrey', 'POR_HORAS', '$8,500 - $10,500 MXN al mes', true, '2026-08-05T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_06', 'seed_ejemplo_company_ventas-comercio', 'Reponedor/a de mercancía', 'Buscamos reponedor/a de mercancía para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Puebla', 'TIEMPO_COMPLETO', '$9,000 - $11,000 MXN al mes', true, '2026-07-29T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_07', 'seed_ejemplo_company_ventas-comercio', 'Asesor/a de ventas telefónicas', 'Buscamos asesor/a de ventas telefónicas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Querétaro', 'TIEMPO_COMPLETO', '$9,500 - $11,500 MXN al mes', true, '2026-07-22T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_08', 'seed_ejemplo_company_ventas-comercio', 'Encargado/a de inventario', 'Buscamos encargado/a de inventario para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Mérida', 'MEDIO_TIEMPO', '$10,000 - $12,000 MXN al mes', true, '2026-07-15T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_09', 'seed_ejemplo_company_ventas-comercio', 'Vendedor/a por catálogo', 'Buscamos vendedor/a por catálogo para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'Tijuana', 'TIEMPO_COMPLETO', '$10,000 - $12,500 MXN al mes', true, '2026-08-22T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_ventas-comercio_10', 'seed_ejemplo_company_ventas-comercio', 'Gerente/a de tienda', 'Buscamos gerente/a de tienda para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'VENTAS_COMERCIO', 'León', 'POR_HORAS', '$10,500 - $12,500 MXN al mes', true, '2026-08-15T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_01', 'seed_ejemplo_company_tecnologia', 'Soporte técnico / mesa de ayuda', 'Buscamos soporte técnico / mesa de ayuda para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Toluca', 'TIEMPO_COMPLETO', '$14,500 - $20,000 MXN al mes', true, '2026-08-08T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_02', 'seed_ejemplo_company_tecnologia', 'Técnico/a en redes', 'Buscamos técnico/a en redes para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Cancún', 'TIEMPO_COMPLETO', '$15,500 - $21,000 MXN al mes', true, '2026-08-01T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_03', 'seed_ejemplo_company_tecnologia', 'Desarrollador/a de software', 'Buscamos desarrollador/a de software para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'San Luis Potosí', 'MEDIO_TIEMPO', '$16,500 - $22,000 MXN al mes', true, '2026-07-25T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_04', 'seed_ejemplo_company_tecnologia', 'Analista de datos', 'Buscamos analista de datos para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Aguascalientes', 'TIEMPO_COMPLETO', '$17,500 - $23,000 MXN al mes', true, '2026-07-18T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_05', 'seed_ejemplo_company_tecnologia', 'Administrador/a de sistemas', 'Buscamos administrador/a de sistemas para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Culiacán', 'POR_HORAS', '$18,500 - $24,000 MXN al mes', true, '2026-08-25T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_06', 'seed_ejemplo_company_tecnologia', 'Técnico/a en reparación de computadoras', 'Buscamos técnico/a en reparación de computadoras para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Chihuahua', 'TIEMPO_COMPLETO', '$19,500 - $25,000 MXN al mes', true, '2026-08-18T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_07', 'seed_ejemplo_company_tecnologia', 'Especialista en ciberseguridad junior', 'Buscamos especialista en ciberseguridad junior para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Veracruz', 'TIEMPO_COMPLETO', '$20,500 - $26,000 MXN al mes', true, '2026-08-11T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_08', 'seed_ejemplo_company_tecnologia', 'Tester / control de calidad (QA)', 'Buscamos tester / control de calidad (qa) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Hermosillo', 'MEDIO_TIEMPO', '$21,500 - $27,000 MXN al mes', true, '2026-08-04T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_09', 'seed_ejemplo_company_tecnologia', 'Técnico/a instalador de internet', 'Buscamos técnico/a instalador de internet para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Oaxaca', 'TIEMPO_COMPLETO', '$22,500 - $28,000 MXN al mes', true, '2026-07-28T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_tecnologia_10', 'seed_ejemplo_company_tecnologia', 'Soporte de e-commerce', 'Buscamos soporte de e-commerce para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'TECNOLOGIA', 'Tampico', 'POR_HORAS', '$23,500 - $29,000 MXN al mes', true, '2026-07-21T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_01', 'seed_ejemplo_company_profesionales', 'Contador/a', 'Buscamos contador/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Ciudad de México', 'TIEMPO_COMPLETO', '$14,500 - $19,000 MXN al mes', true, '2026-08-28T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_02', 'seed_ejemplo_company_profesionales', 'Community manager', 'Buscamos community manager para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Guadalajara', 'TIEMPO_COMPLETO', '$15,500 - $20,000 MXN al mes', true, '2026-08-21T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_03', 'seed_ejemplo_company_profesionales', 'Asistente administrativo/a', 'Buscamos asistente administrativo/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Monterrey', 'MEDIO_TIEMPO', '$16,000 - $21,000 MXN al mes', true, '2026-08-14T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_04', 'seed_ejemplo_company_profesionales', 'Diseñador/a gráfico', 'Buscamos diseñador/a gráfico para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Puebla', 'TIEMPO_COMPLETO', '$17,000 - $22,000 MXN al mes', true, '2026-08-07T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_05', 'seed_ejemplo_company_profesionales', 'Desarrollador/a web junior', 'Buscamos desarrollador/a web junior para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Querétaro', 'POR_HORAS', '$18,000 - $23,000 MXN al mes', true, '2026-07-31T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_06', 'seed_ejemplo_company_profesionales', 'Vendedor/a (ventas B2B)', 'Buscamos vendedor/a (ventas b2b) para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Mérida', 'TIEMPO_COMPLETO', '$19,000 - $23,500 MXN al mes', true, '2026-07-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_07', 'seed_ejemplo_company_profesionales', 'Recursos humanos - reclutador/a', 'Buscamos recursos humanos - reclutador/a para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Tijuana', 'TIEMPO_COMPLETO', '$19,500 - $24,500 MXN al mes', true, '2026-07-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_08', 'seed_ejemplo_company_profesionales', 'Asistente legal', 'Buscamos asistente legal para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'León', 'MEDIO_TIEMPO', '$20,500 - $25,500 MXN al mes', true, '2026-08-24T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_09', 'seed_ejemplo_company_profesionales', 'Encargado/a de servicio al cliente', 'Buscamos encargado/a de servicio al cliente para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Toluca', 'TIEMPO_COMPLETO', '$21,500 - $26,500 MXN al mes', true, '2026-08-17T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "job_postings" ("id", "companyId", "title", "description", "laborCategory", "location", "contractType", "salary", "isActive", "createdAt", "updatedAt")
VALUES ('seed_ejemplo_job_profesionales_10', 'seed_ejemplo_company_profesionales', 'Especialista en marketing digital', 'Buscamos especialista en marketing digital para incorporarse de forma directa. Ofrecemos prestaciones de ley y buen ambiente de trabajo. Se valora experiencia previa en el puesto, responsabilidad y puntualidad. Interesados pueden postularse directamente desde la app.', 'PROFESIONALES', 'Cancún', 'POR_HORAS', '$22,500 - $27,000 MXN al mes', true, '2026-08-10T15:32:49.885Z', CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
